
## AI yardımı ile yazılmıştır

## Clock Sinyali (100 MHz)
set_property PACKAGE_PIN W5 [get_ports clk]							
	set_property IOSTANDARD LVCMOS33 [get_ports clk]
	create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports clk]
 
## Switchler (data_in [15:0])
set_property PACKAGE_PIN V17 [get_ports {data_in[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[0]}]
set_property PACKAGE_PIN V16 [get_ports {data_in[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[1]}]
set_property PACKAGE_PIN W16 [get_ports {data_in[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[2]}]
set_property PACKAGE_PIN W17 [get_ports {data_in[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[3]}]
set_property PACKAGE_PIN W15 [get_ports {data_in[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[4]}]
set_property PACKAGE_PIN V15 [get_ports {data_in[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[5]}]
set_property PACKAGE_PIN W14 [get_ports {data_in[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[6]}]
set_property PACKAGE_PIN W13 [get_ports {data_in[7]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[7]}]
set_property PACKAGE_PIN V2 [get_ports {data_in[8]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[8]}]
set_property PACKAGE_PIN T3 [get_ports {data_in[9]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[9]}]
set_property PACKAGE_PIN T2 [get_ports {data_in[10]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[10]}]
set_property PACKAGE_PIN R3 [get_ports {data_in[11]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[11]}]
set_property PACKAGE_PIN W2 [get_ports {data_in[12]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[12]}]
set_property PACKAGE_PIN U1 [get_ports {data_in[13]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[13]}]
set_property PACKAGE_PIN T1 [get_ports {data_in[14]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[14]}]
set_property PACKAGE_PIN R2 [get_ports {data_in[15]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {data_in[15]}]
 
## 7 Segment Display Katot Pinleri (seg [6:0])
set_property PACKAGE_PIN W7 [get_ports {seg[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[0]}]
set_property PACKAGE_PIN W6 [get_ports {seg[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[1]}]
set_property PACKAGE_PIN U8 [get_ports {seg[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[2]}]
set_property PACKAGE_PIN V8 [get_ports {seg[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[3]}]
set_property PACKAGE_PIN U5 [get_ports {seg[4]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[4]}]
set_property PACKAGE_PIN V5 [get_ports {seg[5]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[5]}]
set_property PACKAGE_PIN U7 [get_ports {seg[6]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {seg[6]}]

## 7 Segment Display Anot Pinleri (r_an [3:0])
set_property PACKAGE_PIN U2 [get_ports {r_an[0]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {r_an[0]}]
set_property PACKAGE_PIN U4 [get_ports {r_an[1]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {r_an[1]}]
set_property PACKAGE_PIN V4 [get_ports {r_an[2]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {r_an[2]}]
set_property PACKAGE_PIN W4 [get_ports {r_an[3]}]					
	set_property IOSTANDARD LVCMOS33 [get_ports {r_an[3]}]

## Orta Buton (btnc - İşlemleri tetiklemek/Debouncer için)
set_property PACKAGE_PIN U18 [get_ports btnc]						
	set_property IOSTANDARD LVCMOS33 [get_ports btnc]